rooms:
  room_A:
    patients:
      - patient_id: P01
        edf_path: fog/data/patients/patient_P01/session_01.edf

      - patient_id: P02
        edf_path: fog/data/patients/patient_P02/session_01.edf

  room_B:
    patients:
      - patient_id: P03
        edf_path: fog/data/patients/patient_P03/session_01.edf

      - patient_id: P04
        edf_path: fog/data/patients/patient_P04/session_01.edf
